version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/hive-io-rest-example
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/hive-io-rest-example

  install_dependencies:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/hive-io-rest-example
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm install --no-optional
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/hive-io-rest-example/node_modules

  test:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/hive-io-rest-example
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Run lint and unit tests
          command: npm test
      - run:
          name: Run coverage report
          command: npm run coverage
      - store_test_results:
          path: ~/hive-io-rest-example/coverage.lcov
      - store_artifacts:
          path: ~/hive-io-rest-example/coverage.lcov

  build:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/hive-io-rest-example
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Build code
          command: npm run build

workflows:
  version: 2
  code-review:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - test
